name: test
on:
  release:
    types: [published]
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
  build_docker:
    needs:
      - build
    runs-on: self-hosted
    steps:
      - name: demo
        run: |
          cd /home/sysadmin
          pwd
          rm -rf demo999
          docker ps -a
          docker images
          git clone https://github.com/AnhMD98/demo999
          ls -la
          cd /home/sysadmin/docker_cloud
          ls -la
          curl -s https://api.github.com/repos/AnhMD98/demo999/releases/latest | grep "/hello.zip" | cut -d '"' -f 4 | wget -i -
          unzip hello.zip
          cp /home/sysadmin/docker_cloud/hello /home/sysadmin/docker_cloud/oauth2srv/
          docker-compose up -d
          
          
